name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: "Description of the release"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
