name: Create Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Bash Script
      run: |
        chmod +x mezeze.sh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: mezeze.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}